In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
import pickle
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer

<h1>Load hasil baca berita</h1>

In [2]:
def loadPickle(name):
    file = open(name, 'rb')
    data = pickle.load(file)
    file.close()
    
    return data

In [3]:
def listOfDictToDataFrame(listOfDict):
    dataFrame = pd.DataFrame(listOfDict)
    
    x = dataFrame.iloc[:, :-1].values
    y = dataFrame.iloc[:, 4].values
    
    return dataFrame, x, y

<h1>Bangun Label encoder</h1>

In [4]:
forY = preprocessing.LabelEncoder()

<h1>Baca Data Test</h1>

In [5]:
def extFeature(words):
    listOfDictFeature = []
    i = 0
    for i in range(len(words)): #iterasi dari awal tiap kata
        dictFeature = {}
        
        dictFeature = inputToDict(words, i)
        
        listOfDictFeature.append(dictFeature)
        
    return listOfDictFeature

def inputToDict(words, i):
    dictFeature = {}
    
    dictFeature['index'] = i    
    dictFeature['first_upper_case'] = isFirstUpper(words[i])
    dictFeature['prev_word'] = isEdge(i, words)
    dictFeature['word'] = words[i]
    
    return dictFeature

def isFirstUpper(word):
    if word[0].isupper():
        return 'y'
    else:
        return 'n'
    
def isEdge(i, words):
    if i == 0:
        return 'null'
    else:
        return words[i-1]

In [6]:
def readPerWord(file):
    words = []
    f = open(file, 'r') #open file
    for line in f:
        words = line.split(' ') #tiap satu baris split per kata
    
    f.close()
    
    words[len(words)-1] = words[len(words)-1].replace('\n',' ')

    return words

<h1>Proses ==============</h1>

In [7]:
data = loadPickle("training.pickle")
dataFrame, x, y = listOfDictToDataFrame(data)

In [8]:
for i in data:
    i.pop("jenis")

In [9]:
v = DictVectorizer(sparse=False)
vectorizedX = v.fit_transform(data)
print(len(vectorizedX),len(vectorizedX[0]))

1198 1399


In [10]:
#forY biar string jadi skala
# forY = preprocessing.LabelEncoder()
# forY.fit(y)
# y = forY.transform(y)
# print(len(y))

<h3>Bangun classifier KNN</h3>

In [11]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(vectorizedX, y, test_size = 0.33, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(vectorizedX, y, test_size = 0.33, shuffle=False)

In [12]:
print(len(X_train),len(X_train[0]))
print(len(X_test),len(X_test[0]))
print(len(y_train))
print(len(y_test))

802 1399
396 1399
802
396


In [13]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [14]:
testWord = readPerWord("test.txt")
listOfDictFeature = extFeature(testWord)
# df = pd.DataFrame(listOfDictFeature)

#mengubah data frame ke list
# newdf = df.iloc[:, :].values

In [15]:
# new_v = DictVectorizer(sparse=False)
vectorizedTest = v.fit_transform(listOfDictFeature)
print(len(vectorizedTest),len(vectorizedTest[0]))

32 63


<h3>Prediksi</h3>

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
print(y_pred)

['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o

In [20]:
y_pred_invers = y_pred
print(y_pred_invers)

['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o'
 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o' 'o

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   7   0   0]
 [  2 349   2   0]
 [  0   5   1   1]
 [  2  23   3   1]]
              precision    recall  f1-score   support

    location       0.00      0.00      0.00         7
           o       0.91      0.99      0.95       353
organization       0.17      0.14      0.15         7
      person       0.50      0.03      0.06        29

    accuracy                           0.89       396
   macro avg       0.39      0.29      0.29       396
weighted avg       0.85      0.89      0.85       396



<h3>Hasil</h3>

In [22]:
newData = []
for i in range(802,1198):
    newData.append(data[i])
    
person = []
location = []
organization = []
for i in range(len(newData)):
    if y_pred_invers[i] == 'person':
        person.append(newData[i]['word'])
    elif y_pred_invers[i] == 'location':
        location.append(newData[i]['word'])
    elif y_pred_invers[i] == 'organization':
        organization.append(newData[i]['word'])

In [23]:
print(person)
print(location)
print(organization)

['Subianto', 'Komisi']
['Menteri', 'Wamenhan', 'Sakti', 'Risma']
['Pertahanan', 'DPR', 'Dahnil', 'Dahnil', 'Arek-arek', 'Daddy']
